apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: registryvtx2838.azurecr.io/userprofile:latest
        envFrom:
        - secretRef:
           name: openhack-secrets
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
          name: userprofile
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  ports:
  - port: 80
  selector:
    app: userprofile
