kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-full-access
  namespace: web
rules:
- apiGroups: ["", "extensions", "apps", "webdevs"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]