kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-full-access
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps", "apidevs"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]