apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: openhackkeyvault69
spec:
  provider: azure
  parameters:
    keyvaultName: "openHackKeyVault69"
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "cc55fe51-0ef6-4297-ace0-de4f6c4162d2"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: SQL-USER
          objectAlias: SQL_USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQL-PASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQL-SERVER
          objectAlias: SQL_SERVER
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQL-DBNAME
          objectAlias: SQL_DBNAME
          objectType: secret
          objectVersion: ""
    tenantId: "31bbbcb2-119e-40d1-b7a8-dea8536f33fb"